<?php  
function random_strings($length_of_string) 
{ 
    // String of all alphanumeric character 
    $str_result = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'; 
    // Shufle the $str_result and returns substring 
    // of specified length 
    return substr(str_shuffle($str_result),  
                       0, $length_of_string); 
} 
$content = $_POST['content'];
$content = str_ireplace("unlink"," ",$content);
$content = str_ireplace("$.ajax","",$content);
$content = str_ireplace("pante","******",$content);
$content = str_ireplace("anjii","******",$content);
$content = str_ireplace(" shit ","******",$content);
$content = str_ireplace("fuck ","******",$content);
$content = str_ireplace("taekk","****",$content);
$content = str_ireplace("taikk","****",$content);
$content = str_ireplace("dafuq","****",$content);
$content = str_ireplace("magnesium sulfat","<strong>magnesium sulfat<strong>",$content);
$content = str_ireplace("bucin","buc*n",$content);
$content = str_ireplace("anjay","an**y",$content);
$content = str_ireplace("konto","******",$content);
$content = str_ireplace("anyii","******",$content);
$content = str_ireplace("anyin","*****",$content);
$content = str_ireplace("kalempo","*****",$content);
$content = str_ireplace("gilo"," **** ",$content);
$content = str_ireplace("emek","****",$content);
$content = str_ireplace("mbut","****",$content);
$content = str_ireplace("kanci","****",$content);
$content = str_ireplace(" asu ","****",$content);
$content = str_ireplace("asu ","****",$content);
$content = str_ireplace(" asu","****",$content);
$content = str_ireplace(" fak ","****",$content);
$content = str_ireplace("fak ","****",$content);
$content = str_ireplace(" fak","****",$content);
$content = str_ireplace(" anjiang ","****",$content);
$content = str_ireplace("anjiang ","****",$content);
$content = str_ireplace(" anjiang","****",$content);
$content = str_ireplace(" anjia","****",$content);
$content = str_ireplace("lande","****",$content);
$content = str_ireplace("kundi","****",$content);
$content = str_ireplace("monto","****",$content);
$content = str_ireplace("baruak","****",$content);
$content = str_ireplace(" tt ","****",$content);
$judul_contents = $_POST['jdl'];
$judul_contents = str_ireplace("unlink"," ",$judul_contents);
$judul_contents = str_ireplace("$.ajax","",$judul_contents);
$judul_contents = str_ireplace("pante","******",$judul_contents);
$judul_contents = str_ireplace("anjii","******",$judul_contents);
$judul_contents = str_ireplace(" shit ","******",$judul_contents);
$judul_contents = str_ireplace("fuck ","******",$judul_contents);
$judul_contents = str_ireplace("taekk","****",$judul_contents);
$judul_contents = str_ireplace("taikk","****",$judul_contents);
$judul_contents = str_ireplace("dafuq","****",$judul_contents);
$judul_contents = str_ireplace("magnesium sulfat","<strong>magnesium sulfat<strong>",$judul_contents);
$judul_contents = str_ireplace("bucin","buc*n",$judul_contents);
$judul_contents = str_ireplace("anjay","an**y",$judul_contents);
$judul_contents = str_ireplace("konto","******",$judul_contents);
$judul_contents = str_ireplace("anyii","******",$judul_contents);
$judul_contents = str_ireplace("anyin","*****",$judul_contents);
$judul_contents = str_ireplace("kalempo","*****",$judul_contents);
$judul_contents = str_ireplace("gilo"," **** ",$judul_contents);
$judul_contents = str_ireplace("emek","****",$judul_contents);
$judul_contents = str_ireplace("mbut","****",$judul_contents);
$judul_contents = str_ireplace("kanci","****",$judul_contents);
$judul_contents = str_ireplace(" asu ","****",$judul_contents);
$judul_contents = str_ireplace("asu ","****",$judul_contents);
$judul_contents = str_ireplace(" asu","****",$judul_contents);
$judul_contents = str_ireplace(" fak ","****",$judul_contents);
$judul_contents = str_ireplace("fak ","****",$judul_contents);
$judul_contents = str_ireplace(" fak","****",$judul_contents);
$judul_contents = str_ireplace(" anjiang ","****",$judul_contents);
$judul_contents = str_ireplace("anjiang ","****",$judul_contents);
$judul_contents = str_ireplace(" anjiang","****",$judul_contents);
$judul_contents = str_ireplace(" anjia","****",$judul_contents);
$judul_contents = str_ireplace("lande","****",$judul_contents);
$judul_contents = str_ireplace("kundi","****",$judul_contents);
$judul_contents = str_ireplace("monto","****",$judul_contents);
$judul_contents = str_ireplace("baruak","****",$judul_contents);
$judul_contents = str_ireplace(" tt ","****",$judul_contents);
$gambar_link = $_POST['lnkgmbr'];
$gambar_link = str_ireplace("unlink"," ",$gambar_link);
$gambar_link = str_ireplace("$.ajax","",$gambar_link);
$gambar_link = str_ireplace("pante","******",$gambar_link);
$gambar_link = str_ireplace("anjii","******",$gambar_link);
$gambar_link = str_ireplace(" shit ","******",$gambar_link);
$gambar_link = str_ireplace("fuck ","******",$gambar_link);
$gambar_link = str_ireplace("taekk","****",$gambar_link);
$gambar_link = str_ireplace("taikk","****",$gambar_link);
$gambar_link = str_ireplace("dafuq","****",$gambar_link);
$gambar_link = str_ireplace("magnesium sulfat","<strong>magnesium sulfat<strong>",$gambar_link);
$gambar_link = str_ireplace("bucin","buc*n",$gambar_link);
$gambar_link = str_ireplace("anjay","an**y",$gambar_link);

$deskrip = $_POST['desk'];
$deskrip = str_ireplace("unlink"," ",$deskrip);
$deskrip = str_ireplace("$.ajax","",$deskrip);
$deskrip = str_ireplace("pante","******",$deskrip);
$deskrip = str_ireplace("anjii","******",$deskrip);
$deskrip = str_ireplace(" shit ","******",$deskrip);
$deskrip = str_ireplace("fuck ","******",$deskrip);
$deskrip = str_ireplace("taekk","****",$deskrip);
$deskrip = str_ireplace("taikk","****",$deskrip);
$deskrip = str_ireplace("dafuq","****",$deskrip);
$deskrip = str_ireplace("magnesium sulfat","<strong>magnesium sulfat<strong>",$deskrip);
$deskrip = str_ireplace("bucin","buc*n",$deskrip);
$deskrip = str_ireplace("anjay","an**y",$deskrip);
$deskrip = str_ireplace("konto","******",$deskrip);
$deskrip = str_ireplace("anyii","******",$deskrip);
$deskrip = str_ireplace("anyin","*****",$deskrip);
$deskrip = str_ireplace("kalempo","*****",$deskrip);
$deskrip = str_ireplace("gilo"," **** ",$deskrip);
$deskrip = str_ireplace("emek","****",$deskrip);
$deskrip = str_ireplace("mbut","****",$deskrip);
$deskrip = str_ireplace("kanci","****",$deskrip);
$deskrip = str_ireplace(" asu ","****",$deskrip);
$deskrip = str_ireplace("asu ","****",$deskrip);
$deskrip = str_ireplace(" asu","****",$deskrip);
$deskrip = str_ireplace(" fak ","****",$deskrip);
$deskrip = str_ireplace("fak ","****",$deskrip);
$deskrip = str_ireplace(" fak","****",$deskrip);
$deskrip = str_ireplace(" anjiang ","****",$deskrip);
$deskrip = str_ireplace("anjiang ","****",$deskrip);
$deskrip = str_ireplace(" anjiang","****",$deskrip);
$deskrip = str_ireplace(" anjia","****",$deskrip);
$deskrip = str_ireplace("lande","****",$deskrip);
$deskrip = str_ireplace("kundi","****",$deskrip);
$deskrip = str_ireplace("monto","****",$deskrip);
$deskrip = str_ireplace("baruak","****",$deskrip);
$deskrip = str_ireplace(" tt ","****",$deskrip);
$aut = $_POST['aut'];
$aut = str_ireplace("unlink"," ",$aut);
$aut = str_ireplace("$.ajax","",$aut);
$aut = str_ireplace("pante","******",$aut);
$aut = str_ireplace("anjii","******",$aut);
$aut = str_ireplace(" shit ","******",$aut);
$aut = str_ireplace("fuck ","******",$aut);
$aut = str_ireplace("taekk","****",$aut);
$aut = str_ireplace("taikk","****",$aut);
$aut = str_ireplace("dafuq","****",$aut);
$aut = str_ireplace("bucin","buc*n",$aut);
$aut = str_ireplace("anjay","an**y",$aut);
$aut = str_ireplace("unli78",'official<i class="fa fa-check"></i>',$aut);
$nike =random_strings(5);
$items =(string)$nike."B";
$handle = fopen("bgl/cnt/{$items}.php","w");
fwrite($handle,$content);
fclose($handle);
$handle2 = fopen("bgl/jdl/{$items}.txt","w");
fwrite($handle2,$judul_contents);
fclose($handle2);
$handle4 = fopen("bgl/gbr/{$items}.txt","w");
fwrite($handle4,$gambar_link);
fclose($handle4);
$handle5 = fopen("bgl/des/{$items}.txt","w");
fwrite($handle5,$deskrip." #".date("d-m-Y"));
fclose($handle5);
$handle6 = fopen("bgl/aut/{$items}.txt","w");
fwrite($handle6,$aut);
fclose($handle6);
$handle7 = fopen("bgl/cnt/kom/{$items}.txt","w");
fclose($handle7);
$handle8 = fopen("bgl/cnt/kom/{$items}.php","w");
$sdsds = file_get_contents('bgl/cnt/kom/tas.txt');
fwrite($handle8,$sdsds);
fclose($handle8);
setcookie("test_cookie", $items, time() + (86400 * 30), '/');
setcookie("users", $aut, time() + (86400 * 30), '/');
if (isset($_POST['check1'])) {
        $files = "bgl/skab.txt";
        $current = file_get_contents($files);
        $current =  preg_replace('/^[ \t]*[\r\n]+/m', '', $current);
        $current .= trim($items," ")."\n";
        file_put_contents($files, $current);
}
if (isset($_POST['submit'])){
echo "<script>window.location.replace('index.php');</script>";
}
?>
<script>
window.open('pst.php');
</script>