<?php 
$sa = "http://$_SERVER[HTTP_HOST]$_SERVER[REQUEST_URI]"; 
$namea = basename($sa);
$usr = $_POST['usr'];
$usr = str_ireplace("unli78",'official<i class="fa fa-check"></i>',$usr);
$fadeda = str_replace("/kom","",$sa);
$faded = str_replace(".php",".txt",$namea);
$content = $_POST['infos'];
$content = str_ireplace("unlink"," ",$content);
$content = str_ireplace("$.ajax","",$content);
$content = str_ireplace("pante","******",$content);
$content = str_ireplace("anjii","******",$content);
$content = str_ireplace(" shit ","******",$content);
$content = str_ireplace("fuck ","******",$content);
$content = str_ireplace("anjay","an**y",$content);
$content = str_ireplace("kont","******",$content);
$content = str_ireplace("anyii","******",$content);
$content = str_ireplace("anyin","*****",$content);
$content = str_ireplace("kalempo","*****",$content);
$content = str_ireplace("gilo"," **** ",$content);
$content = str_ireplace("emek","****",$content);
$content = str_ireplace("mbut","****",$content);
$content = str_ireplace("kanci","****",$content);
$content = str_ireplace(" asu ","****",$content);
$content = str_ireplace("asu ","****",$content);
$content = str_ireplace(" asu","****",$content);
$content = str_ireplace(" fak ","****",$content);
$content = str_ireplace("fak ","****",$content);
$content = str_ireplace(" fak","****",$content);
$content = str_ireplace(" anjiang ","****",$content);
$content = str_ireplace("anjiang ","****",$content);
$content = str_ireplace(" anjiang","****",$content);
$content = str_ireplace(" anjia","****",$content);
$content = str_ireplace("lande","****",$content);
$content = str_ireplace("kundi","****",$content);
$content = str_ireplace("monto","****",$content);
$content = str_ireplace("baruak","****",$content);
$currenta = file_get_contents($faded);
$currenta .= $usr.' : ' .$content."\n";
setcookie("ese", $usr, time() + (86400 * 30), '/');
file_put_contents($faded, $currenta);
header("Location: $fadeda");
?>